---
apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
  annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-myapp: "kv/myapp"
        vault.hashicorp.com/agent-inject-template-myapp: |
          {{- with secret "kv/myapp" }}
          username: {{ .Data.username }}
          password: {{ .Data.password }}
          {{ end }}
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/service: "http://vault.vault.svc:8200"
        vault.hashicorp.com/tls-skip-verify: "true"
spec:
  serviceAccountName: myapp
  restartPolicy: Never
  containers:
    # Nginx container
    - name: nginx
      image: nginx
